### ISSUE TITLE
Coordinates and ETA

### ISSUE THREAD

**Issue by styfle** [concurlabs/geoslack#1]
Would it be possible to also respond with coordinates?

Or better yet, add an environment variable such as `DESTINATION_COORDINATES` and then the slack message can say something like A's location is 3 miles from destination (find the distance between A's coordinates and the destinations coordinates).

**Comment by styfle** [comment]
@ismaelc What are your thoughts on this?

**Comment by styfle** [comment]
I'm working on this feature in my own repo here: https://github.com/styfle/geoslack/issues/3

**Comment by ismaelc** [comment]
Ok good stuff
